name: Build and Test
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses:
          AdoptOpenJDK/install-jdk@v1
        with:
          version: '14'
      - name: Build and Test
        run: ./gradlew test